### ISSUE TITLE
Create a 3D Logo For Devify

### ISSUE THREAD

**Issue by DevishaPadmaperuma** [Smilin-Dominator/Devify#28]

**Comment by NotSoEpicGuy** [comment]
i'll recreate the current logo in 3D

**Comment by NotSoEpicGuy** [comment]
what file format should I export this as?

**Comment by Smilin-Dominator** [comment]
Up to you. I encourage you to test the logo with the resources class.

**Comment by Smilin-Dominator** [comment]
Also @NotSoEpicGuy, can you make 3 logos? One for;
- Main screen
- Verifying 
- Hashing

**Comment by NotSoEpicGuy** [comment]
> Up to you. I encourage you to test the logo with the resources class.

I dont really see how i can export a 3D logo as an image file through blender, 

>Also @NotSoEpicGuy, can you make 3 logos? One for;

Main screen
Verifying
Hashing

i'll see what I can do

**Comment by Smilin-Dominator** [comment]
Then research how to display Blender 3D Models in Java

**Comment by NotSoEpicGuy** [comment]
I'll need some help with that, I can't seem to find/understand anything

**Comment by DevishaPadmaperuma** [comment]
https://stackoverflow.com/questions/18853053/how-can-i-display-a-3d-model-in-jframe

**Comment by NotSoEpicGuy** [comment]
I have to learn OpenGL to do that?
